package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
)

func main() {
	var buf bytes.Buffer

	buf.WriteString(`
	// Code generated by go generate; DO NOT EDIT.
// This file was generated by genconstants.go

package main
	`)
	buf.WriteString("\n")

	buf.WriteString("const(\n")
	ver := os.Args[1]

	buf.WriteString(fmt.Sprintf("Version = \"%s\"\n", ver))
	name := os.Args[2]

	buf.WriteString(fmt.Sprintf("Name = \"%s\"\n", name))

	title := os.Args[3]
	buf.WriteString(fmt.Sprintf("Title = \"%s\"\n", title))

	buf.WriteString(")\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		panic(err)
	}

	os.WriteFile("const.go", src, 0644)
}
